version: '3.3'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    env_file:
      - .env
    restart: always
    network_mode: host
