version: '3.3'

services:
  streamlit-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8501:8501"
    environment:
      - PORT=8501
    restart: always

  # flask-server:
  #   build:
  #     context: .
  #     dockerfile: ./flask_server.Dockerfile
  #   ports:
  #     - "5001:5001"
  #   restart: always
