services:
  - type: web
    name: streamlit-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    domains:
      - dashboard.dicasaimobiliaria.com.br
    envVars:
      - key: PORT
        value: 8501
    healthCheckPath: /_stcore/health

  - type: web
    name: flask-server
    env: docker
    plan: free
    dockerfilePath: ./flask_server.Dockerfile
    autoDeploy: true
    domains:
      - webhook.dicasaimobiliaria.com.br

