# Exported from Render on 2025-04-15T14:06:04Z
services:
- type: web
  name: dicasa-dashboard
  runtime: docker
  repo: https://github.com/oarthurdev/python-dicasa-dashboard
  plan: free
  envVars:
  - key: ACCESS_TOKEN_KOMMO
    sync: false
  - key: KOMMO_API_URL
    sync: false
  - key: VITE_SUPABASE_URL
    sync: false
  - key: VITE_SUPABASE_ANON_KEY
    sync: false
  region: oregon
  healthCheckPath: /_stcore/health
  dockerContext: .
  dockerfilePath: ./Dockerfile
  domains:
  - dashboard.dicasaimobiliaria.com.br

- type: web
  name: flask-server
  env: docker
  plan: free
  dockerfilePath: ./flask_server.Dockerfile
  autoDeploy: true
  domains:
    - webhook.dicasaimobiliaria.com.br
    
version: "1"
